/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiBlankAiRouteImport } from './routes/api/blank-ai'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlankAiRoute = ApiBlankAiRouteImport.update({
  id: '/api/blank-ai',
  path: '/api/blank-ai',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/blank-ai': typeof ApiBlankAiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/blank-ai': typeof ApiBlankAiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/blank-ai': typeof ApiBlankAiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/blank-ai'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/blank-ai'
  id: '__root__' | '/' | '/api/blank-ai'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiBlankAiRoute: typeof ApiBlankAiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blank-ai': {
      id: '/api/blank-ai'
      path: '/api/blank-ai'
      fullPath: '/api/blank-ai'
      preLoaderRoute: typeof ApiBlankAiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiBlankAiRoute: ApiBlankAiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
